#! /bin/sh
ROOT=$(dirname $0)/..
LIST="\
	${ROOT}/rust/prebuilt/proxmox/librust-*_arm64.deb \
	${ROOT}/proxmox/build/librust-*_arm64.deb \
"

rsync -ra /usr/share/cargo/registry/* usr/share/cargo/registry

for i in ${LIST}
do
  dpkg-deb -x $i .
done
