language: rust

matrix:
  include:
    - rust: nightly
      script: cargo test
      env: RUSTFLAGS='--cfg async_trait_nightly_testing'
    - rust: beta
      script: cargo test
    - rust: stable
      script: cargo check
