language: rust
rust:
  - 1.45.0
  - stable
  - beta
  - nightly
sudo: required
dist: bionic
#cache: cargo
# Needed for codecov reporting
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - libssl-dev
env: RUST_BACKTRACE=full
before_script:
  - cargo install --force cargo-when
  - |
    if [ "$TRAVIS_RUST_VERSION" == "1.45.0" ]; then
      rustup component add clippy
      rustup component add rustfmt
    elif [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
      cargo install --force cargo-audit
    fi
script:
  # Newer dependency versions don't support rustc 1.45, so we use a Cargo.lock file for those
  # builds.
  - |
    if [ "${TRAVIS_RUST_VERSION}" == "1.45.0" ]; then
      cp Cargo-1.45.lock Cargo.lock
    fi
  - cargo test --tests --examples
  - cargo test --doc
  - cargo test --all-features
  - cargo when --equals TRAVIS_RUST_VERSION=1.45.0 clippy --all --all-features -- --deny warnings
  - cargo when --equals TRAVIS_RUST_VERSION=1.45.0 fmt --all -- --check
  - cargo when --equals TRAVIS_RUST_VERSION=stable audit
after_success: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin &&
  cargo tarpaulin --out Xml &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
notifications:
  email:
    on_success: never
