language: rust
rust:
  - 1.45.0
  - stable
  - beta
  - nightly
sudo: false
#cache: cargo
before_script:
  - cargo install --force cargo-when
  - rustup target add wasm32-unknown-unknown
  - |
    if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
      cargo install --force cargo-audit
    elif [ "$TRAVIS_RUST_VERSION" == "1.45.0" ]; then
      rustup component add clippy
      rustup component add rustfmt
    fi
script:
  # Newer dependency versions don't support rustc 1.45, so we use a Cargo.lock file for those
  # builds.
  - |
    if [ "${TRAVIS_RUST_VERSION}" == "1.45.0" ]; then
      cp Cargo-1.45.lock Cargo.lock
    fi
  - cargo test --tests --examples
  - cargo test --doc
  - cargo test --all-features
  # Curl without reqwest (examples will not build)
  - cargo test --tests --features curl --no-default-features
  - cargo when --equals TRAVIS_RUST_VERSION=1.45.0 fmt --all -- --check
  - cargo when --equals TRAVIS_RUST_VERSION=1.45.0 clippy --all --all-features -- --deny warnings
  - cargo when --equals TRAVIS_RUST_VERSION=stable audit
  - cargo check --target wasm32-unknown-unknown
notifications:
  email:
    on_success: never
